name: Pull Request

on:
  pull_request:
    branches: [main]
    paths-ignore:
      - 'docs/**'
      - '**.md'
      - 'LICENSE'

jobs:
  test:
    name: Tests
    uses: ./.github/workflows/test.yaml

  publish:
    name: Publish Docker image
    needs: test
    uses: ./.github/workflows/docker_publish.yaml
    secrets:
      AWS_PRODUCTION_ACCOUNT_ID: ${{ secrets.AWS_PRODUCTION_ACCOUNT_ID }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
